Feature/alembic/bin 25
val0326/Binance pull request #10
Opened 2024-10-14 09:35 UTC by val0326

Install & tuning alembic

2024-11-01 07:59 UTC, Badasper requested changes

2024-11-01 07:59 UTC, Badasper commented on src/apps/users/routers.py
> +sys.path.append("..")
тут что-то пошло не так
в продовом коде не должно быть таких хаков

2024-11-01 07:59 UTC, Badasper commented on src/apps/users/routers.py
> +sys.path.append("..")
при запуске приложения текущий каталог запуска становится корневым 
такое возможно еще в алембике прописывать , оно к работе приложения не относится

2024-11-01 07:59 UTC, Badasper commented on src/database.py
> +SQLALCHEMY_DATABASE_URL = "sqlite:///./db.sqlite3"
такое лучше выносить в переменные окружения / settings

2024-11-01 07:59 UTC, Badasper commented on src/database.py
> +def create_db_and_tables():
такое норм в самом начале , чтобы не прикручивать алембик
но этим должен заниматься алембик 
далее ты это в маин вызываешь
так незя

2024-11-01 07:59 UTC, Badasper commented on src/main.py
> +    create_db_and_tables()
каждый пуск приложения будет пытаться создать базу

2024-11-01 07:59 UTC, Badasper commented on src/tests/test_user.py
> +from dotenv import load_dotenv
в папке tests не хватает `"__init__.py"`

2024-12-02 07:37 UTC, val0326 commented on src/apps/users/routers.py
> +sys.path.append("..")
Пока не нашел решения данной проблемы, вернул к прежнему варианту,

2024-12-02 16:05 UTC, Badasper approved these changes

2024-12-02 16:07 UTC, Badasper commented
для тестовых данных делают фикстуры в папке tests
<img width="450" alt="image" src="https://github.com/user-attachments/assets/3df5578a-1f4a-4181-bbb6-dd0e14e8e19d">


короче двигай дальше


create-all нужон если олембиком не создаешь миграцию

2024-12-02 16:07 UTC, merged